### ISSUE TITLE
A better way to initialize data.

### ISSUE THREAD

**Issue by jcblw** [honeinc/hone-sdk#10]
Right now im seeing an _decorateData

https://github.com/honeinc/hone-sdk/blob/master/src/datastore.js#L129

as a way to add the data stuff to an object. There probably should be a way to access this functionality  and have a better api. eg.

```javascript
hone.load( 'quiz', obj );
```

I have no idea what key is in that function which make me afraid to use it.

**Comment by andyburke** [comment]
_decorateObject adds the .save() method to an object (and caches the object's type and key (id) inside the object for later internal use).

You definitely should not need to use _decorateObject, __type or __key externally.

What would you want hone.load( 'quiz', obj ) to do? Load a quiz based on some fields in obj? It's not clear to me what you're looking to do.

**Comment by andyburke** [comment]
Are you looking to create a quiz? The create() method takes any initial data you want it to have:

https://github.com/honeinc/hone-sdk/blob/master/docs/DataStore.md#methods.create

**Comment by jcblw** [comment]
Im trying to use it for our app, but the intial load of a quiz object is just a plain object. I need to load it up to be able to use the save method on it.

**Comment by jcblw** [comment]
or use it as if an object that was returned from the sdk

**Comment by andyburke** [comment]
I see. If you don't fetch the quiz using the SDK's get() method, that's not really supported. I suppose we could expose that functionality, but in the long run I question wether that's something we'd want to support or if we'd just want to convert everything to use hone.get()

**Comment by jcblw** [comment]
eh i know this thing was going to be bad with cache.

**Comment by andyburke** [comment]
I mean, you keep saying that, but I don't understand what's bad. In time we will switch everything to use the SDK which has both an internal cache and eliminates the data subsystem code we need to update things when holding references.

**Comment by andyburke** [comment]
@jcblw can you tell me exactly what you're trying to do? it seems like there's some miscommunication that's causing confusion, either for one or both of us.

**Comment by jcblw** [comment]
#11 created, so the first thing to get our app to do this is to use it as the state, issue is at the start of the app we already have the plain jane quiz object, by design it makes voting faster. So upon saving it to the `hone.state.set` I realized it would not have the save method on it. So I looked for a method in data to just add it to the cache and found `_decorateObject`. Which I really dont like very first thing I do with the SDK which is use a private method. So the PR fixes that by proxing the method to a differnt method ( not private ) with a better api. Also adds in a test to make sure we know if that is broken.

**Comment by andyburke** [comment]
I see. I forgot that we sent the JSON quiz on initial render. Exposing a public way to decorate an object is probably the best way to handle this. I'll look over the PR tonight.
